# netlify.toml
[build]
  command = "npm install && CI=false npm run build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20"
  REACT_APP_BACKEND_URL = "https://sheelaa-chatbot-backend.onrender.com" 